repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
        args:
        - --maxkb=512
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: pretty-format-json
        args:
        - --autofix
      - id: requirements-txt-fixer
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.30.0
    hooks:
      - id: markdownlint-fix
