name: Run tests

on:
  push:
    branches: [ develop, master, main ]
  pull_request:

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Run tests
        shell: bash
        run: |
          echo "Python version is $(python -V)"
          pip install --upgrade pip poetry
          chmod +x run_tests.sh
          ./run_tests.sh
